fastlane_version '2.217.0'

desc 'ensure_git_branch set to dev for now, need better setup'
before_all do
  ensure_git_branch(
    branch: 'dev'
  )
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.trippyadvisor.MusicShare', type: 'development', readonly: true)
    # match(app_identifier: 'com.trippyadvisor.MusicShare', type: 'appstore', readonly: true)
  end

  desc 'build the iOS application'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: './ios/MusicShare.xcodeproj')
    gym(scheme: 'MusicShare', export_method: 'development', workspace: './ios/MusicShare.xcworkspace')
  end

  desc 'ship to testflight'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/MusicShare.xcodeproj')
    push_to_git_remote
  end
end

platform :android do
  # android lanes
  # desc 'build the android application'
  # private_lane :build do
  #   gradle(task: 'clean', project_dir: 'android/')
  #   gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  # end
  # desc 'ship to playstore beta'
  # lane :beta do
  #   build
  #   supply(track: 'beta', track_promote_to: 'beta')
  #   git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
  #   push_to_git_remote
  # end
end
