fastlane_version '2.217.0'

desc 'ensure_git_branch set to dev for now, need better setup'
before_all do
  ensure_git_branch(
    branch: 'dev'
  )
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.app.bundle', type: 'development', readonly: true)
    match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: true)
  end
end

platform :android do
  # android lanes
end
